### ISSUE TITLE
Not a issue but a question, and i also didnt knew where to put it

### ISSUE THREAD

**Issue by Kuritzu** [coylz/TobiiStreamEngineForJava#12]
Hello, I am a master's research student at the University of Coimbra currently doing some researcher with Tobii 4c eye-tracker. I have a question regarding whether you needed any kind of license to obtain the coordinates of the gaze. I'm currently trying to play with it in MatLab but every type of data regarding gaze seems to be limited with Tobi Pro SDK. Did you use Tobii Pro SDK?

Thanks for your time

**Comment by schwabdidier** [comment]
As mentioned on the main page, we use the Tobii Core SDK Stream Engine API https://developer.tobii.com/product-integration/stream-engine/

**Comment by Tohaker** [comment]
Direct Matlab integration may require some form of license, but you can use the stream engine to record eye movement and write something in Matlab to replay it back? They also have example programs written in C# to get the eye position without any kind of license
